### ISSUE TITLE
What is the license for nodejitsu/docs?

### ISSUE THREAD

**Issue by cxw42** [nodejitsu/docs#94]
I can't find a LICENSE or other statement in this repo of what the license is.  May I copy and paste code samples out of the docs?  They are, after all, incredibly useful :+1: .  Would the authors please add licensing information, or point me to where it is that I'm missing?  Thanks!

**Comment by sukrosono** [comment]
ping and :ear:

**Comment by jcrugzz** [comment]
[`LICENSE`](https://github.com/nodejitsu/docs/blob/master/LICENSE)

**Comment by indexzero** [comment]
Yes. LICENSE file is in the root directory.
